#ifndef ALTACORE_AST_HPP
#define ALTACORE_AST_HPP

#include "ast-shared.hpp"

#include "ast/node.hpp"
#include "ast/statement-node.hpp"
#include "ast/expression-node.hpp"
#include "ast/root-node.hpp"
#include "ast/expression-statement.hpp"
#include "ast/type.hpp"
#include "ast/parameter.hpp"
#include "ast/block-node.hpp"
#include "ast/function-definition-node.hpp"
#include "ast/return-directive-node.hpp"
#include "ast/integer-literal-node.hpp"
#include "ast/variable-definition-expression.hpp"
#include "ast/accessor.hpp"
#include "ast/fetch.hpp"
#include "ast/assignment-expression.hpp"
#include "ast/boolean-literal-node.hpp"
#include "ast/binary-operation.hpp"
#include "ast/import-statement.hpp"
#include "ast/function-call-expression.hpp"
#include "ast/string-literal-node.hpp"
#include "ast/function-declaration-node.hpp"
#include "ast/attribute-node.hpp"
#include "ast/literal-node.hpp"
#include "ast/attribute-statement.hpp"
#include "ast/conditional-statement.hpp"
#include "ast/conditional-expression.hpp"
#include "ast/class-definition-node.hpp"
#include "ast/class-statement-node.hpp"
#include "ast/class-member-definition-statement.hpp"
#include "ast/class-method-definition-statement.hpp"
#include "ast/class-special-method-definition-statement.hpp"
#include "ast/class-instantiation-expression.hpp"
#include "ast/pointer-expression.hpp"
#include "ast/dereference-expression.hpp"
#include "ast/while-loop-statement.hpp"
#include "ast/cast-expression.hpp"
#include "ast/class-read-accessor-definition-statement.hpp"
#include "ast/character-literal-node.hpp"
#include "ast/type-alias-statement.hpp"

#endif // ALTACORE_AST_HPP
